### ISSUE TITLE
Make AutoDoc Conditional

### ISSUE THREAD

**Issue by sardanaaman** [ciscomanagedservices/sxo-autodoc#1]
There may be situations when a developer may not want all workflow descriptions as defined in SXO to reflect in their GitHub README. For example, larger projects may have workflows within workflows with only the parent workflow having user-facing documentation.

Could we add support for a conditional check (perhaps using a stipulated local boolean variable defined at the workflow level, defaults to `true`) that controls if AutoDoc runs against a workflow or not?

**Comment by nxmbiar** [comment]
Has been added in the latest commit
